### ISSUE TITLE
Exclude file types

### ISSUE THREAD

**Issue by bhitney** [alekdavis/PlexBackup#13]
Would be great to exclude file types, most notably .bif files (video preview thumbnails).  If they are enabled, they are mingled in with the Media folder, and consume about 30GB of space on my system.  They can be regenerated if needed by Plex.

**Comment by alekdavis** [comment]
Good idea. I'll give it a thought.

**Comment by alekdavis** [comment]
@bhitney Apparently, PowerShell's `Compress-Archive` does not allow excluding files (and the workaround to first `Get-ChildItem` and pipe results into `Compress-Archive -Update` not only 1000 times slower, but also messes up the archive). If you have an idea on how to make `Compress-Archive` exclude file types, let me know; otherwise, I'll make it work with `7-zip` compression and `robocopy`.

**Comment by bhitney** [comment]
Ah I was afraid of that as I hadn't used Compress-Archive before.  Personally I use 7zip, but in thinking about Compress-Archive and doing a little google-fu, one possibility might be to copy all the files to a staging directory and then compress -- something like this: https://www.petri.com/custom-archiving-powershell-5-0 -- of course, this is similar to just doing a robocopy of everything and then compressing it.  Not an ideal approach, could be that filtering is simply not a usable option when using Compress-Archive?

**Comment by obviex** [comment]
Yeah, copying is not an acceptable workaround.

**Comment by alekdavis** [comment]
Implemented in v1.5.3.
