### ISSUE TITLE
Restore Error

### ISSUE THREAD

**Issue by Galiwyx** [alekdavis/PlexBackup#22]
Hello,

I restored a backup, all seems ok but I had an error, sorry It's in French : 
L'opération a réussi.  => The operation is a success.

reg : L'opération a réussi.
Au caractère D:\PlexBackup-master\PlexBackup.ps1:2692 : 13
             reg import $backupRegKeyFilePath *>&1 | Out-Null
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (L'opération a réussi.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Is that bad ? Thank you

**Comment by alekdavis** [comment]
Not bad. It's French, man. :-)  What happens here is that sometimes (and I'm not sure what the reason here: a PowerShell version or something else), the import of registry key command generates an exception with the message saying that everything is okay. So I have code to capture the error message, but it obviously only works for English version of the OS:

```PowerShell
try {
    reg import $backupRegKeyFilePath *>&1 | Out-Null
}
catch {
    if ($_.Exception -and
        $_.Exception.Message -and
        ($_.Exception.Message -match "^The operation completed successfully")) {
        # This is a bogus error that only appears in PowerShell ISE, so ignore.
        return $true
    }
    else {
        LogException $_
    }
    return $false
}
```
So you can ignore it. If you have any ideas how to make it more robust, let me know.

**Comment by Galiwyx** [comment]
Okay, thank you for your answer. Unfortunately, I don’t have knowledge to help you :(
