### ISSUE TITLE
Backup fails with TaskScheduler

### ISSUE THREAD

**Issue by shanester64** [alekdavis/PlexBackup#58]
Running Win10
From the log file..
Stopping Plex Media Server process:
  Plex Media Server.exe
Error stopping Plex Media Server. ERROR: The process "Plex Media Server.exe" with PID XXX could not be terminated.

Running with highest permissions.

**Comment by alekdavis** [comment]
I assume it works if you run it manually, right? If so, it means the process is not running with highest permissions when invoked from the scheduler.

**Comment by shanester64** [comment]
Yes, It works manually.It is running at highest privileges




 

Thanks,

Ken Shane

 
 

    On Thursday, March 3, 2022, 10:09:37 PM CST, Alek Davis ***@***.***> wrote:  
 
 


I assume it works if you run it manually, right? If so, it means the process is not running with highest permissions when invoked from the scheduler.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alekdavis** [comment]
What happens if you run it from the Actions panel in the Task Scheduler?

**Comment by shanester64** [comment]
Thank for your quick reply, much appreciated.The first run was a one time schedule. After the first failure I have been running it manually, trying different options with the same results, 

 

Thanks,

Ken Shane

 
 

    On Friday, March 4, 2022, 03:48:02 AM CST, Alek Davis ***@***.***> wrote:  
 
 


What happens if you run it from the Actions panel in the Task Scheduler?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alekdavisintel** [comment]
Hey, Ken. I wish I could help you, but I really do not know why this would happen. Obviously, when the script runs from the Task Scheduler, it does not have enough privileges to stop services, even though you say the option is checked. Task Scheduler is a weird beast (it has other issues as well), but I do not have sufficient knowledge to troubleshoot it over message exchange (and even in person). I would check Windows Even log to see if there are any more specific errors. Maybe there is some policy applied to the account that you use that prevents this. Really hard to say. I can explain what, how and why the script does what it does, but the Task Scheduler part is not really my area of expertise, especially since I have not heard from anyone about this particular issue since I released the script a few years ago. I wish I could be more helpful.

**Comment by albino1** [comment]
If it's some sort of Task Scheduler specific permission issue maybe hide it in a batch script and just call the batch script instead?

**Comment by alekdavisintel** [comment]
I'm not sure what you're saying, but I'm sure it will not help.

**Comment by albino1** [comment]
I'm saying if Task Scheduler has a permission issue of some sort, then just have Task Scheduler run a batch script with the PowerShell line inside of it, then the PowerShell line is being executed independently of any theoretical Task Scheduler restrictions.

To be clear, I don't think it will work either, but I also don't think Task Scheduler should have any problems in the first place, especially if it works when you just right-click and run it from inside of Task Scheduler.

**Comment by alekdavis** [comment]
That's not how Windows security works (I mean your assumption about this being helpful). In essence, it's already what happens: Task Scheduler invokes PowerShell (scripting), which runs the backup script. You can introduce 100 more scripts in between (Task Scheduler-script 1-script2-...-script 100-PowerShell-backup script), but it will not be of much use.

**Comment by albino1** [comment]
Apologies, I was hoping it would maybe be a possible workaround, but yeah, not an option.
