### ISSUE TITLE
PlexBackup Fails to load the config file

### ISSUE THREAD

**Issue by cjr71244** [alekdavis/PlexBackup#65]
Hello. Great Script.

I'm having an issue loading the config file. 

here's what I tried. I imagine I'm missing something simple.

PS F:\Rclone\Plexbackup Powershell Script> .\PlexBackup.ps1 -ConfigFile "PlexBackup.ps1"
Cannot import run-time settings from configuration file 'PlexBackup.ps1'. The variable cannot be validated because the
 value ps1 is not a valid value for the Format variable.

PS F:\Rclone\Plexbackup Powershell Script> .\PlexBackup.ps1 -ConfigFile "PlexBackup.ps1.json"
Cannot import run-time settings from configuration file 'PlexBackup.ps1.json'. Config file 'PlexBackup.ps1.json' is no
t found.

PS F:\Rclone\Plexbackup Powershell Script> \PlexBackup.ps1 -ConfigFile "F:\Rclone\Plexbackup Powershell Script\PlexBackup.ps1.json"
\PlexBackup.ps1 : The term '\PlexBackup.ps1' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At line:1 char:1
+ \PlexBackup.ps1 -ConfigFile "F:\Rclone\Plexbackup Powershell Script\P ...
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (\PlexBackup.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by alekdavis** [comment]
Your first call fails because `PlexBackup.ps1` is the name of the script, not the config file.

Your second call fails because it looks like the config file does not exist in the current directory.

Your third call fails because you forgot the period before the backslash (you need to invoke the script as `.\PlexBackup.ps1`, not `\PlexBackup.ps1`.

Have you tried following the instructions at the Getting started section (https://github.com/alekdavis/PlexBackup/blob/master/GETTING%20STARTED.md)?
