### ISSUE TITLE
plex doesn't start after backup finish, code 87 incorrect parameter

### ISSUE THREAD

**Issue by ManuJapan89** [alekdavis/PlexBackup#67]
Hi,
i recently updated plex pms machine to windows 11 22h2
i ran plebackup.ps1 today for the 1st time and i got this error at the end of backup process
PS C:\WINDOWS\system32> cd W:\PlexBackup-master\PlexBackup-master
PS W:\PlexBackup-master\PlexBackup-master> .\PlexBackup.ps1 -Mode Backup -Type 7zip -LogLevel Debug -Log -ErrorLog -Keep 1
ERRORE RUNAS: impossibile eseguire - C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
87: Parametro non corretto.

PS W:\PlexBackup-master\PlexBackup-master>
error runas: impossible to execute
87 incorrect parameter

Can you help me?

Thanks

**Comment by alekdavis** [comment]
Try rebooting the computer and run PlexBackup with additional flags: `-Verbose -Debug`. Then share all output.

**Comment by ManuJapan89** [comment]
Hi Alek, i'll do it 
system rebooted,here a screen of uptime on task manager and the powershell command as admin
![image](https://user-images.githubusercontent.com/82624098/201042938-cd72effb-b288-4ea8-ada0-5b5e7321ee38.png)
Other info:
this system run simultaneously :
Plex
Tautulli
Docker(Hyper-V mode)
Sonarr
Jdownloader2
The AV is the default MS Defender, configured with configuredefender(github) in HIGH mode security
The windows version with winver command is this:
![image](https://user-images.githubusercontent.com/82624098/201043426-cc2c71fa-afa7-4220-ac23-79980575467c.png)
Anyway i'll run the backup as per your indication and keep you updated with the output

**Comment by ManuJapan89** [comment]
Here : https://pastebin.com/CJBGCnZ2
you'll find the output requested

Thanks

**Comment by alekdavis** [comment]
Thanks for the info. Unfortunately, I do not have a Windows 11 with Plex installed (my system does not allow upgrade to Windows 11). Basically, you get this error when the script is trying to execute the command on line 2338 (in the current version):

```
runas /trustlevel:0x20000 "$Script:PlexServerPath"
```

I suspect, it must be some internal bug in Windows, possibly due to a localized Windows version, similar to the one reported here: https://learn.microsoft.com/en-us/answers/questions/741503/runas-fail.html

For now, I'd recommend first making sure you have the latest Windows build. If you do, try running this command form an elevated PowerShell session (run PowerShell as Administrator) manually. As the last parameter, you can pass the full path to the Plex Media Server executable or some built-in program, such as Notepad.exe (make sure the path is enclosed in double quotes).

If it fails, I'd report it top Microsoft (I'd leave Plex out of it, just say the command does not work for Notepade or some built-in app). In the meantime, you can try changing lines 2337 and 2338 in the PlexBackup.ps1 script from
```
# Start-Process $plexServerExePath -LoadUserProfile
runas /trustlevel:0x20000 "$Script:PlexServerPath"
```
to
```
Start-Process $Script:PlexServerExePath -LoadUserProfile
# runas /trustlevel:0x20000 "$Script:PlexServerPath"
```
This may introduce other issues, or maybe it won't. Let me know.

**Comment by ManuJapan89** [comment]
Hi Alek, i'll try when i have time
But, if the backup succeded as i suppose looking at the backup.log
the fact that the backup script.ps1 doesn't run plex media server  again after finish is not an issue at all. at least for me.
Do you expect issue on restore or everything will be fine? 
i usually use this command for restore: .\PlexBackup.ps1 -Mode Restore -Type 7zip -LogLevel Debug -Log -ErrorLog -NoRestart
Anyway, here is the backup log : https://pastebin.com/Czs73R9N

**Comment by alekdavis** [comment]
The restore should work fine. The only issue seems to be with this particular command that tries to launch PMS after backup, and I use a hack to do this because that's what seem to be the recommended way (I want to make sure PMS does not start as Administrator). Hopefully, it's a Windows update bug that gets fixed.

**Comment by mpk99** [comment]
This is happening to me as well, same build (win11 etc).

Can we not find a way to just launch plex as a regular user after the backup is done?  i tried 

`Start-Process $Script:PlexServerPath -LoadUserProfile
# runas /trustlevel:0x20000 `"$Script:PlexServerPath"``

As suggested and it didn't fix it for me.

**Comment by alekdavis** [comment]
Thank you @mpk99. Good info.

**Comment by alekdavis** [comment]
Added a workaround in https://github.com/alekdavis/PlexBackup/releases/tag/v2.1.7.
