### ISSUE TITLE
Validation error. Backup version does not match

### ISSUE THREAD

**Issue by cjr71244** [alekdavis/PlexBackup#72]
Hello, I've been using the script for a while now. I have it running on a regular basis. 
A little over a month ago it stopped working.

I ran it manually and got this error
"Validation error. Backup version '1.29.2.6364' does not match version '1.31.1.6733' of the Plex Media Server. To ignore version check, run the script with the '-NoVersion' flag.
"

I'd like to try and fix the error instead of running with no version. Any suggestions?

**Comment by alekdavis** [comment]
When the script runs, it should write to the log files, so to see the error, you do not need to run it manually. But since you did run it manually, it looks like you are running it in the `Restore` mode. I assume you are trying to run a backup, not a restore, operation, right? So the restore mode operation must be set somewhere: on command line or config file. And if you want to perform a restore operation, the error is valid.

**Comment by cjr71244** [comment]
You were right, I had the restore flag set in the json file. I changed it to backup and it seems to be working. Glad I found that, that means all the time I thought it was backing up I was restoring. 
Thank you. You can close this now.
 
 
  On Wed, Mar 1, 2023 at 6:58 PM, Alek ***@***.***> wrote:   


When the script runs, it should write to the log files, so to see the error, you do not need to run it manually. But since you did run it manually, it looks like you are running it in the Restore mode. I assume you are trying to run a backup, not a restore, operation, right? So the restore mode operation must be set somewhere: on command line or config file. And if you want to perform a restore operation, the error is valid.

**Comment by cjr71244** [comment]
Fixed, user error
