### ISSUE TITLE
question/enhancement

### ISSUE THREAD

**Issue by jimlynnjulian** [alekdavis/PlexBackup#78]
Does the script use timestamp comparisons to reduce the amount of copying in a scheduled backup?
Thanks.

**Comment by alekdavis** [comment]
Timestamp comparison of what? I'm not sure what exactly you are looking for and why.

**Comment by alekdavis** [comment]
If you use the `Robocopy` option, I think it will only copy the changed files, but for the compressed backup (default or 7-zip), unless I'm missing something, timestamp makes no sense. Say, you do full backup on March 1st, then you do another backup on March 15th. Are you suggesting that the second backup should only include files changed (added or updated) since the first backup? What about deleted files, e.g. when you delete some media? I think what you are asking is something like differential backup in windows. If so, no we do not do this for a number of reasons. One, it takes longer to do differential backup than the full backup. Second, for it to work, you need to keep both the full backup and all incremental backups. What if you lose one of them? And what if between full backup Plex changes the database structure, so you will end up with different versions of info between full and incremental backups. Just too many problems, not to mention the complexity of the backup logic. The goal is to make each backup result self-contained, so you can restore the data from each one of them. But if your primary goal is to reduce the amount of copying, use the `Robocopy` option in the `Continue` mode and it will do just that.

**Comment by jimlynnjulian** [comment]
If a record of timestamps of files is kept, this could be used as an indicator of state of change and, therefore what needs to be saved/updated. No point in copying the same unaltered file over and over. A list of folders would also be useful should the existing folder structure change. This idea was inspired by diff files used by some,  in software source updates
Of course, a. You already do this; b. The time taken is longer than a mass copy. It may be a simple trade off between storage space and speed.

**Comment by jimlynnjulian** [comment]
Questions addressed. Thank you.
