### ISSUE TITLE
Allow 7-Zip Compression

### ISSUE THREAD

**Issue by blevins321** [alekdavis/PlexBackup#8]
Any thoughts on allowing the (optional?) use of 7zip as the compression method using the portable edition? In a few anecdotal tests, 7zip compressed my metadata folder in about 2/3 the time as the powershell compression currently used. It also resulted in a noticable-but-not-groundbreaking reduction in file size if that matters to others.

**Comment by alekdavis** [comment]
I thought about it and decided that while 7-zip it may be somewhat more efficient, the efficiency gains doe not really justify additional complexity. Say, I add 7-zip, but then someone asks: why not offer RAR support?  Or use PeaZip, az well? I mean, if this were a real-time app that would greatly benefit from speed/space improvements, then sure, but we're talking about a backup, that in a typical case would run as a scheduled job at night, so who cares if it takes one hour or an hour and a half and wastes a bit more space? While the current solution is not the most efficient option, it has no dependencies on any third party software. And it already has more command-line switches that I wish it had. Anyway, I am still thinking about it and if there is a convincing case, I can give it a try (or someone else may want to cheap in, since it's an open source app and all code is available), but as of the time of writing, the case seems weak to me.

**Comment by blevins321** [comment]
All fair points :)  I might try giving it a go in the next couple weeks (new-ish to Powershell). In my case, my backup took about 8 hours via PlexBackup, and about 5.5 hours just manually doing the 7zip GUI for the same folders. It'd be worth it to me, because that's 2.5 hours Plex doesn't have to be offline (I have users in 12 different time zones).

**Comment by alekdavis** [comment]
Oh, I see. That's a long time. And this is what mine used to take when I had the app data running on a NAS, but once I moved app data to a local drive it went from 5 or so hours down to about an hour. Anyway, if you give me command line switches/examples for: (a) full backup, (2) differential backup, and (c) restore, I'll give it a shot when I have time (not now, though).

**Comment by alekdavis** [comment]
@blevins321: I added support for 7-zip, but haven't checked in the code, yet. Want to give it a try?

**Comment by alekdavis** [comment]
Okay, support or 7-zip compression added. Feel free to test. (It's faster and produces smaller files in my tests.)

**Comment by alekdavis** [comment]
Just tested it at home and, wow: it took 1/3 of the time (13 minutes vs about 40 minutes it took in the past). Also files are smaller. Media and cache are just slightly smaller but metadata is less than half size. Thanks for the good suggestion.
