### ISSUE TITLE
Sub folders not being created by backup process

### ISSUE THREAD

**Issue by Desert-Rat-Comander** [alekdavis/PlexBackup#88]
I use your script to do nightly backup of my Plex Environment.  Works Great!.  I recently changed the target of the backup to a new 
disk.  I changed the json to point to the new disk and the script runs with out error but does not create a sub director as it did in the past.  This behavior exists when running the PlexBackup.ps1 script in an elevated command window or using the task schedular.

Any Ideas??

**Comment by alekdavisintel** [comment]
@Desert-Rat-Comander Please run with the `--Verbose --Debug` flags (in addition to the normal flags) and post the script output along with your config file (if there is any).

**Comment by Desert-Rat-Comander** [comment]
Thanks for the quick response. 

I ran the script with verbose and debug.  The console output ( attached ) shows the verbose text.  The behavior did not change.  There were no new entries in the backup directory.  I have attached the console output, A snip of the output directory, and the jason file.

Thanks
![Backup Dirrectory List](https://github.com/alekdavis/PlexBackup/assets/79155388/074cde4c-45af-4977-becc-1acffd5290bd)
[PlexBackup.ps1.json](https://github.com/alekdavis/PlexBackup/files/15284039/PlexBackup.ps1.json)
[Plex_Console_logs.txt](https://github.com/alekdavis/PlexBackup/files/15284040/Plex_Console_logs.txt)

**Comment by alekdavis** [comment]
@Desert-Rat-Comander Set the value of the `BackupDir` setting in the JSON file to `null` and run again.

NOW:

```
 "BackupDir": {
        "_meta": {
            "default": null
        },
        "value": "D:\\0-Plex_Daily_Backup"
    },
```
CHANGE TO:
```
 "BackupDir": {
        "_meta": {
            "default": null
        },
        "value": null
    },
```

**Comment by Desert-Rat-Comander** [comment]
I did as you specified and that resolved my issue.  I've included the latest files in case you would like to see the output.   I would appreciate knowing how that action resolved the issue.  I did not point any of the script or jason to the backup directory and the result was what I desired.  How did the script resolve the pathing to the backup directory?  Thanks for the help!!
[PlexBackup.ps1.json](https://github.com/alekdavis/PlexBackup/files/15284462/PlexBackup.ps1.json)
[Plex_Console_logs2.txt](https://github.com/alekdavis/PlexBackup/files/15284463/Plex_Console_logs2.txt)
![Backup Dirrectory List2PNG](https://github.com/alekdavis/PlexBackup/assets/79155388/e650e636-8f8e-4ed8-a665-75f66c59523c)

**Comment by alekdavis** [comment]
There are two configuration settings that specify where the backup files go: `BackupRootDir` and `BackupDirPath`. Normally, you should use `BackupRootDir`, because when you do, the script will create a backup subfolder for each run (with the execution timestamp). On restore, the script will automatically detect the latest backup based on the subfolder name reflecting the backup date and time. If you specify a value in the `BackupDirPath`, there will be no timestamped subfolders created and the backup files will be always created in the same location (so there will be just one backup subfolder). The `BackupDirPath` is mostly intended for the restore operation, in case you want to restore files from a non-default folder, so in most cases, it must be empty. Makes sense?
